server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cloth_app"
    username: ${DATASOURCE_NAME:root}
    password: ${DATASOURCE_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver  # Thêm dòng này để đảm bảo MySQL Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: daithien2004@gmail.com
    password: mhynmvjndddebqzg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

open:
  api:
    title: API document
    version: v1.0.0
    description: Mo ta
    serverUrl: http://localhost:8080
    serverName: server
